version: '3.9'

services:
  frontend:
    build: ../week6/1-12
    ports:
      - "5000:5000"

  backend:
    build: ../week6/1-13
    ports:
      - "8080:8080"
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=cache

  cache:
    image: redis:6-alpine
